version: "3"
services:
  web:
    image: webdevops/php-apache-dev:7.0
    ports:
      - "8080:80"
    volumes:
      - "./:/app"
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:5.5.3"
    environment:
      - xpack.security.enabled=false